pipeline {
    agent {
        label 'k8s-slave' 
    }
    environment {
        GKE_DEV_CLUSTER_NAME = "cart-cluster"
        GKE_DEV_ZONE = "us-west1-a"
        GKE_DEV_PROJECT = "delta-sprite-416312"
    }
    stages {
        stage ('Authenticate to Google Cloud GKE') {
            steps {
                echo "Executing in Google Cloud auth stage"
                script {
                    //gke_cluster_name, gke_zone, gke_project 
                    auth_login("${env.GKE_DEV_CLUSTER_NAME}", "${env.GKE_DEV_ZONE}", "${env.GKE_DEV_PROJECT}").call()
                    }  
                }
            }
        stage('Checkout') {
            steps {
              git credentialsId: 'my-credentials-id', url: 'https://github.com/KondaVenkateswarlu11/Inc42Media.git', branch: 'master'


            }
        }
        stage('Deploy MySQL') {
            steps {
                script {
                    auth_login("${env.GKE_DEV_CLUSTER_NAME}", "${env.GKE_DEV_ZONE}", "${env.GKE_DEV_PROJECT}").call()

                                    // This deploys the MySQL service to your Kubernetes cluster
                    sh '''
                        cd Inc42Media/WordPressProject/
                        kubectl apply -f 1-storageclass.yaml
                        kubectl apply -f 2-mysql-pvc.yaml
                        kubectl apply -f 4-mysql-secret.yaml
                        kubectl apply -f 5-mysql-deploy.yaml
                        kubectl apply -f 6-mysql-svc.yaml

                    '''
                }
            }
        }

        stage('Deploy WordPress') {
            steps {
                script {
                    auth_login("${env.GKE_DEV_CLUSTER_NAME}", "${env.GKE_DEV_ZONE}", "${env.GKE_DEV_PROJECT}").call()
                    // This deploys the WordPress service to your Kubernetes cluster
                    sh '''
                        kubectl apply -f 3-wordpress-pvc.yaml
                        kubectl apply -f 7-wordpress-deploy.yaml
                        kubectl apply -f 8-wordpress-svc.yaml
                        
                    '''
                }
            }
        }
    }
}



def auth_login(gke_cluster_name, gke_zone, gke_project) {
    return {
        echo "Entering Authentication method for GKE Cluster Login"
        sh "gcloud config set account jenkins@delta-sprite-416312.iam.gserviceaccount.com"
        # gcloud auth activate-service-account jenkins@nice-carving-411801.iam.gserviceaccount.com --key-file=key.json
        sh "gcloud compute instances list"
        echo "************* Listing Number of Nodes in K8S *************"
        sh "gcloud container clusters get-credentials $gke_cluster_name --zone $gke_zone --project $gke_project"
        sh "kubectl get nodes"

    }     
}